version: '3.8'

services:
  nginx:
    image: nginx:1.23-alpine
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/backend/static/
      - media_volume:/app/media/
    depends_on:
      - web

  web:
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    entrypoint: /app/docker/backend/server-entrypoint.sh
    volumes:
      - static_volume:/app/backend/static/
      - media_volume:/app/media/
    expose:
      - "8000"
    environment:
      DEBUG: "True"
      CELERY_BROKER_URL: "redis://redis:6379/0"
      CELERY_RESULT_BACKEND: "redis://redis:6379/0"
      DJANGO_DB: postgresql
      DATABASE_ENGINE: django.db.backends.postgresql_psycopg2
      DATABASE_HOST: db
      DATABASE_NAME: postgres
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_PORT: 5432

  worker:
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    entrypoint: /app/docker/backend/worker-entrypoint.sh
    volumes:
      - static_volume:/app/backend/static/
      - media_volume:/app/media/
    environment:
      DEBUG: "True"
      CELERY_BROKER_URL: "redis://redis:6379/0"
      CELERY_RESULT_BACKEND: "redis://redis:6379/0"
      DJANGO_DB: postgresql
      DATABASE_ENGINE: django.db.backends.postgresql_psycopg2
      DATABASE_HOST: db
      DATABASE_NAME: postgres
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_PORT: 5432
    depends_on:
      - web
      - redis

  redis:
    image: redis:7.0.5-alpine
    expose:
      - "6379"

  db:
    image: postgres:13.0-alpine
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    expose:
      - "5432"

volumes:
  static_volume: 
  media_volume: 
  postgres_data:
