# Generated by Django 5.0.6 on 2024-06-18 21:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorpatientassignment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_patients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='doctorpatientassignment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_doctors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='results',
            name='asignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='patients.doctorpatientassignment', verbose_name='Назначение'),
        ),
        migrations.AlterUniqueTogether(
            name='doctorpatientassignment',
            unique_together={('doctor', 'patient')},
        ),
    ]
